CREATE TABLE IF NOT EXISTS website_banners (
  id INT PRIMARY KEY AUTO_INCREMENT,
  image VARCHAR(500) NOT NULL,
  alt_text VARCHAR(255) NOT NULL DEFAULT 'Banner',
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (created_by) REFERENCES admins(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
